### ISSUE TITLE
Andere Werte steuern

### ISSUE THREAD

**Issue by DcFamas** [Schlauer-Hax/homebridge-iobroker#1]
Hallo Schlauer-Hax,
danke für deine Integration in Homebridge.
Ist es auch möglich andere Werte außer an/aus anzusteuern?
Gerne würde ich auch die Helligkeit und Farbtemperatur ändern. 

Danke für deine Hilfe und Grüße!
DcFamas

**Comment by Schlauer-Hax** [comment]
Hi,
aktuell leider noch nicht aber ich glaube dass lässt sich ganz einfach integrieren.

**Comment by DcFamas** [comment]
Hey Schlauer-Hax,
ich habe tatsächlich überhaupt keine Ahnung von der Programmierung.
Der Java Kurs in der Uni hat mir den letzten Rest gegeben. Habe mir dennoch deinen Quellcode angeschaut, in der Hoffnung, dass ich ggf. irgendetwas verstehe, aber allein diese "this." (wie in Java) haben mir die Nackenhaare (ich glaube die Dinger waren für die Konstruktoren?!) aufstehen lassen.

Wäre es entsprechend für dich möglich die Dinge zu implementieren?

Grüße und Danke für deine kommende Antwort
DcFamas

**Comment by Schlauer-Hax** [comment]
Hey,

na klar, ich werde es mir demnächst mal anschauen, auch wenn ich es gerade schwer testen kann.

Viele Grüße

**Comment by Schlauer-Hax** [comment]
Hi,
die beiden Werte kann man jetzt mit in der config angeben und diese werden auch geschrieben.

**Comment by elmocito** [comment]
@Schlauer-Hax : Kann man auch andere Werte steuern, die z.B. dann die Remote Einstellung von HomeKit verwenden?

Use Case: Ich will unsere Lüftungsanlage manuell steuern können.
Dafür gibt es unterschiedliche States
Lüftungsstufe: 0-4
Lüftungssteuerung: Automatik / Manuell

Das wäre mega.

**Comment by Schlauer-Hax** [comment]
Hi, das müsste sich man mal anschauen und überlegen inwiefern man den Code anpassen müsste aber ich denke das ist möglich.
